### ISSUE TITLE
cannot login; variable $_SESSION is cleared, the login_request variable is lost

### ISSUE THREAD

**Issue by defeden** [bodleian/Aeolus#1]

**Comment by ahankinson** [comment]
Hello, This project is considered unsupported, and no fixes to it will be made.

**Comment by defeden** [comment]
i have fixed the problem by inserting the following line application_entity.php@startup before session_start()

session_set_cookie_params (0, '/', '', false, false);

my browser doesn't send PHPSESSID when using http, so the application creates a new session each time, with this line, the browser is forced to send PHPSESSID even over http.
